all:
	g++ -o Socket.o -c Socket.cpp
	g++ -o enttecdmxusb.o -c enttecdmxusb.cpp
	g++ -o rs232.o -c rs232.cpp
	g++ -o testEnttecDMXUSBPRO.o -c testEnttecDMXUSBPRO.cpp
	g++ -o serveur Socket.o enttecdmxusb.o rs232.o testEnttecDMXUSBPRO.o
